In [1]:
import numpy as np

In [2]:
matrix = np.array ([np.arange (3), [i for i in range(1 ,4)],[6 ,7 ,8]])

In [3]:
print(matrix)

[[0 1 2]
 [1 2 3]
 [6 7 8]]


In [4]:
matrix [1,0]

1

In [5]:
matrix [0] = 42

In [6]:
print(matrix)

[[42 42 42]
 [ 1  2  3]
 [ 6  7  8]]


In [7]:
matrix [1:3]

array([[1, 2, 3],
       [6, 7, 8]])

In [8]:
matrix [ ]

SyntaxError: invalid syntax (<ipython-input-8-3dc980572451>, line 1)

In [ ]:
matrix [1:]


In [ ]:
matrix [1:100]

In [ ]:
matrix [:]

In [ ]:
matrix [1: ,:2]

In [ ]:
matrix [:2, 1:]

In [ ]:
matrix.ravel ()

In [ ]:
matrix [: ,1].copy ()

In [ ]:
matrix[1].tolist()


In [ ]:
matrix.reshape(-1)



In [ ]:
matrix = np.array ([np.arange (3), [i for i in range(1 ,4)],[6 ,7 ,8]])
print(matrix)


In [ ]:
np.sqrt(matrix)


In [ ]:
np.exp(matrix)


In [ ]:
np.min(matrix)


In [ ]:
np.max(matrix, axis=1)


In [ ]:
np.min(np.maximum(np.random.randn(4),np.random.randn(4)))


In [ ]:
np.mean(matrix)


In [ ]:
np.mean(matrix, axis=0)


In [ ]:
np.sum(matrix)


In [ ]:
np.invert(matrix)


In [ ]:
np.random.randn(5)


In [ ]:
np.trace(matrix)


In [ ]:
import pandas as pd # import pandas module as pd


In [ ]:
s = pd.Series([1,4,-2,'home'],index=['a','b','c','d'])


In [ ]:
s.dtype

In [ ]:
s.dtypes

In [ ]:
data={'population':[1.5,1.2,2.0,1.4,0.8],'state':['Nevada','Florida','Ohio','Texas','Florida'],'year':[2003,2000,2004,1990,1994]}

In [ ]:
df=pd.DataFrame(data,index=['one','two','three','four','five'],columns=
['year','state','population','debt'])

In [ ]:
print(df)

In [ ]:
s[1:3]

In [ ]:
s[0]


In [ ]:
s['d']

In [ ]:
s.values[2:]

In [ ]:
df[['population','state']]

In [ ]:
df.population

In [ ]:
df.iloc[1:]

In [ ]:
df.iloc[2:4:,2:5]

In [ ]:
df.loc['one']

In [ ]:
df.debt=34.67

In [ ]:
print(df)

In [ ]:
df.debt=[df.iloc[:,2][i]*5 for i in range(0,df.shape[0])]

In [ ]:
print(df)

In [ ]:
df.head()

In [ ]:
df.tail(2)

In [ ]:
df.sample(n=3)

In [ ]:
df['newColomn']=pd.Series(np.random.randn(df.shape[0]),index=df.index)

In [ ]:
print(df)


In [ ]:
df.drop_duplicates('state')


In [ ]:
df.state


In [ ]:
df=pd.read_csv('sampleDataSet.csv') # without setting names

In [ ]:
df=pd.read_csv('sampleDataSet.csv’,names=['a','b','c','d','e','f','g','h','i']) # setting names

In [9]:
a=np.array([1,2,3])

In [10]:
print(a)

[1 2 3]


In [11]:
a.dtype # return the data type of the array


dtype('int32')

In [12]:
matrix = np.array ([np.arange (3), [i for i in range(1 ,4)],[6 ,7 ,8]])


In [13]:
print(matrix)

[[0 1 2]
 [1 2 3]
 [6 7 8]]


In [14]:
np.zeros((5,2,2),dtype=float) # array of all zero of float data type


array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [32]:
np.ones((4,5)) # array full of one’s


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.empty([3,4]) #array which initial content is random


array([[6.67483769e-312, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [6.23060404e-307, 1.54800582e+185, 2.64420575e+180,
        8.97916543e-067],
       [1.46151730e+165, 3.57807651e-061, 4.43137220e+175,
        2.48828705e+180]])

In [17]:
np.arange (2 ,10 ,2) # array with evenly spaced values


array([2, 4, 6, 8])

In [18]:
np.arange (2 ,10 ,1).reshape(4,2) #rearranging the size of the array


array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [19]:
np.full ([2 ,3] , 4) # creates an array with constant values


array([[4, 4, 4],
       [4, 4, 4]])

In [20]:
np.eye(3) # creates an identity matrix


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.linspace (2 ,3,5) # creates an evenly spaced array within specified


array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [22]:
np.copy(matrix) #returns the copy of the object


array([[0, 1, 2],
       [1, 2, 3],
       [6, 7, 8]])

In [23]:
matrix.copy() #deep copy


array([[0, 1, 2],
       [1, 2, 3],
       [6, 7, 8]])

In [24]:
matrix.view() #shallow copy


array([[0, 1, 2],
       [1, 2, 3],
       [6, 7, 8]])

In [33]:
matrix.sort()
print(matrix)

[[0 1 2]
 [1 2 3]
 [6 7 8]]


In [26]:
matrix.sort(axis=1) #sort along the specified axis


In [27]:
print(matrix)

[[0 1 2]
 [1 2 3]
 [6 7 8]]


In [29]:
matrix [0: ,:1] # 2D array slicing


array([[0],
       [1],
       [6]])

In [30]:
matrix [:2, 0:2]


array([[0, 1],
       [1, 2]])

In [31]:
matrix [:1, :]


array([[0, 1, 2]])